version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_test_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/app_db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: php_test_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: